
#pragma once

// Components list - must have at least one element
//
#define _CMPS_LIST_ \
	ANIMATIONCOMPONENT, \
	BULLETDATA, \
	BULLET_COLLISION_COMPONENT, \
	BUTTON, \
	CAMERA, \
	CAMERA_CLAMP, \
	CAMERA_FOLLOW, \
	COLLISION_REGISTRATION_BY_ID, \
	COLLISIONABLE, \
	CONTACT_MANIFOLD, \
	DECK, \
	DYN_IMAGE, \
	DYN_IMAGE_WITH_FRAMES, \
	ENEMYSTATEMACHINE, \
	ENEMY_TRIGGERER, \
	SYNCHRONIZE, \
	FLIPXCONTROLLER, \
	FOG, \
	FOG_COLLISION_COMPONENT, \
	FOLLOW, \
	GAMEPAD_PLAYER_CTRL, \
	GENERAL_HUD, \
	HEALTH, \
	ID_COMPONENT, \
	IMAGE, \
	KEYBOARDPLAYERCTRL, \
	LIFETIMETIMER, \
	MANA, \
	MOVEMENTCONTROLLER, \
	MYTHICCOMPONENT, \
	MYTHICDATACOMPONENT, \
	OFFSET_DYN_IMAGE, \
	PLAYER_HUD, \
	PLAYER_TRIGGERER, \
	RATATOUILLE_COLLISION_COMPONENT, \
	RECT, \
	RENDER_ORDERING, \
	REWARDDATACOMPONENT, \
	ROTATIONCOMPONENT, \
	GHOSTSTATE,\
	RIGIDBODY, \
	SIMPLEMOVE, \
	STATEMACHINE, \
	TRANSFORM, \
	TRANSFORMLESS_DYN_IMAGE, \
	TRIGGER_MANIFOLD, \
	WEAPON, \
	WAVEMANAGER, \
	MULTIPLAYER_HUD, \
	DAMAGE_POPUP, \
	ERASE_TEXTURE, \
	DUMB_WAVE_MANAGER

// Groups list - must have at least one element
//
#define _GRPS_LIST_ \
	BULLET, \
	DECKBUTTON, \
	DECKINFO, \
	ENEMY, \
	ENEMYBULLETS, \
	MYMYTHICOBJS, \
	MYTHICOBJS, \
	PLAYER, \
	PLAYERBULLETS, \
	REWARDCARDS, \
	REWARDDECK, \
	STAR_DROP, \
	TUTORIALPOPUPS, \
	UI, \
	WEAPONBUTTON, \
	WEAPONINFO, \
	DAMAGE_POPUPS

// Scene list
//
#define _SCENE_LIST_ \
	GAMESCENE,\
	MAINMENUSCENE,\
	MYTHICSCENE,\
	SELECTIONMENUSCENE,\
	GAMEOVERSCENE,\
	VICTORYSCENE,\
	REWARDSCENE,\
	MULTIPLAYERMENUSCENE,\
	TUTORIALSCENE

// Handlers list - must have at least one element
//
#define _HDLRS_LIST_ \
	CAMERA, \
	CONFIRMMYTHIC, \
	CONFIRMREWARD, \
	EXCHANGEBUTTON, \
	FOGGROUP, \
	GAMEINFO, \
	HUD_ENTITY, \
	MYTHICINFO, \
	NEXTROUNDMYTHIC, \
	NEXTROUNDREWARD, \
	PLAYER, \
	REWARDHEALTH, \
	REWARDINFO, \
	TOGAMEBUTTON, \
	TURORIALHUD, \
	TUTORIALBUTTON, \
	TUTORIALPLAYER, \
	WAVE, \
	WEAPONINFO

